import {
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpRight,
  Bell,
  Box,
  Building2,
  Calendar,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ClipboardCheck,
  Command,
  Copy,
  Download,
  Ellipsis,
  ExternalLink,
  Filter,
  Headphones,
  HelpCircle,
  Laptop,
  LayoutDashboard,
  Link,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Monitor,
  Moon,
  Package,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Smartphone,
  Sun,
  Tablet,
  Tag,
  Upload,
  Users,
  Wrench,
  X,
  AlertCircle,
  Circle,
  Clock,
  CheckCheck,
  List,
  ArrowDown,
  ArrowUp,
  Archive,
  FileText,
  Eye,
} from "lucide-react";

const icons = {
  "arrow-down-left": ArrowDownLeft,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-right-left": ArrowRightLeft,
  "arrow-up-right": ArrowUpRight,
  bell: Bell,
  box: Box,
  "building-2": Building2,
  calendar: Calendar,
  "chart-no-axes-combined": ChartNoAxesCombined,
  check: Check,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "clipboard-check": ClipboardCheck,
  command: Command,
  copy: Copy,
  download: Download,
  ellipsis: Ellipsis,
  "external-link": ExternalLink,
  filter: Filter,
  headphones: Headphones,
  "help-circle": HelpCircle,
  laptop: Laptop,
  "layout-dashboard": LayoutDashboard,
  link: Link,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  monitor: Monitor,
  moon: Moon,
  package: Package,
  pencil: Pencil,
  plus: Plus,
  "refresh-cw": RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  smartphone: Smartphone,
  sun: Sun,
  tablet: Tablet,
  tag: Tag,
  upload: Upload,
  users: Users,
  wrench: Wrench,
  x: X,
  "alert-circle": AlertCircle,
  circle: Circle,
  clock: Clock,
  "check-check": CheckCheck,
  list: List,
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  archive: Archive,
  "file-text": FileText,
  eye: Eye,
};

export function Icon({
  name = "box",
  size = 18,
  className = "",
  strokeWidth = 1.65,
  ...props
}) {
  const Glyph = icons[name] || Box;
  return (
    <Glyph
      size={size}
      strokeWidth={strokeWidth}
      className={`icon ${className}`}
      aria-hidden="true"
      {...props}
    />
  );
}

export default Icon;
