/**
 * REACT APPLICATION ENTRY POINT
 * 
 * This is the first file that runs when the React app loads.
 * It's responsible for:
 * 1. Importing React and necessary dependencies
 * 2. Finding the root HTML element
 * 3. Rendering the App component into that element
 * 
 * This file is typically auto-generated by Vite/Create React App,
 * but understanding it helps you understand how React works!
 */

// StrictMode is a React development tool that helps find potential problems
// It doesn't render anything visible, but runs extra checks in development
import { StrictMode } from 'react'

// createRoot is the modern way to render React apps (React 18+)
// Older versions used ReactDOM.render()
import { createRoot } from 'react-dom/client'

// Import global CSS styles - this applies styles to the entire app
// THIS LINE IS CRITICAL - without it, Tailwind CSS won't work!
import './index.css'

// Import the main App component - this is the root of our component tree
import App from './App.jsx'

/**
 * RENDER THE APPLICATION
 * 
 * createRoot() creates a React root for the specified DOM element.
 * The root element is defined in index.html (usually <div id="root"></div>)
 * 
 * .render() renders the App component into that root element.
 * 
 * React will:
 * 1. Find the element with id="root" in index.html
 * 2. Replace its contents with the App component
 * 3. Manage all updates and re-renders from there
 * 
 * StrictMode wraps App to enable additional development checks:
 * - Identifies components with unsafe lifecycles
 * - Warns about legacy string ref API usage
 * - Detects unexpected side effects
 */
createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)